Labfiles/01_Restaurant_begin/Client/Controllers/JobApplicationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Http;
using Client.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class JobApplicationController : Controller
    {
        private IHttpClientFactory _httpClientFactory;

        public JobApplicationController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await PopulateEmployeeRequirementsDropDownListAsync();
            return View();
        }
        private async Task PopulateEmployeeRequirementsDropDownListAsync()
        {
            HttpClient httpClient = _httpClientFactory.CreateClient();
            httpClient.BaseAddress = new Uri("http://localhost:54517");
            HttpResponseMessage response = await httpClient.GetAsync("api/RestaurantWantedAd");
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<EmployeeRequirements> employeeRequirements = await response.Content.ReadAsAsync<IEnumerable<EmployeeRequirements>>();
                ViewBag.EmployeeRequirements = new SelectList(employeeRequirements, "Id", "JobTitle");
            }
        }
        public IActionResult ThankYou()
        {
            return View();
        }
    }
}

Labfiles/01_Restaurant_begin/Client/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Http;
using Client.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class ReservationController : Controller
    {
        private IHttpClientFactory _httpClientFactory;

        public ReservationController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await PopulateRestaurantBranchesDropDownListAsync();
            return View();
        }
        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> CreatePostAsync(OrderTable orderTable)
        {
            HttpClient httpclient = _httpClientFactory.CreateClient();
            HttpResponseMessage response = await httpclient.PostAsJsonAsync("http://localhost:54517/api/Reservation", orderTable);
            if (response.IsSuccessStatusCode)
            {
                OrderTable order = await response.Content.ReadAsAsync<OrderTable>();
                return RedirectToAction("ThankYouAsync", new { orderId = order.Id });
            }
            else
            {
                return View("Error");
            }
        }
        private async Task PopulateRestaurantBranchesDropDownListAsync()
        {
            HttpClient httpClient = _httpClientFactory.CreateClient();
            httpClient.BaseAddress = new Uri("http://localhost:54517");
            HttpResponseMessage response = await httpClient.GetAsync("api/RestaurantBranches");
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<RestaurantBranch> restaurantBranches = await response.Content.ReadAsAsync<IEnumerable<RestaurantBranch>>();
                ViewBag.RestaurantBranches = new SelectList(restaurantBranches, "Id", "City");
            }
        }
        public async Task<IActionResult> ThankYouAsync(int orderId)
        {
            HttpClient httpClient = _httpClientFactory.CreateClient();
            httpClient.BaseAddress = new Uri("http://localhost:54517");
            HttpResponseMessage response = await httpClient.GetAsync("api/Reservation/" + orderId);
            if (response.IsSuccessStatusCode)
            {
                OrderTable orderResult = await response.Content.ReadAsAsync<OrderTable>();
                return View(orderResult);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

Labfiles/01_Restaurant_begin/Client/Controllers/RestaurantBranchesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using Client.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class RestaurantBranchesController : Controller
    {
        private IHttpClientFactory _httpClientFactory;

        public RestaurantBranchesController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        public async Task<IActionResult> Index()
        {
            HttpClient httpClient = _httpClientFactory.CreateClient();
            httpClient.BaseAddress = new Uri("http://localhost:54517");
            HttpResponseMessage response = await httpClient.GetAsync("api/RestaurantBranches");
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<RestaurantBranch> restaurantBranches = await response.Content.ReadAsAsync<IEnumerable<RestaurantBranch>>();
                return View(restaurantBranches);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

Labfiles/01_Restaurant_begin/Client/Controllers/WantedAdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Client.Models;

namespace Client.Controllers
{
    public class WantedAdController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Labfiles/01_Restaurant_begin/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/restaurant-style.css" rel="stylesheet" />
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/menu-active.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark navbar-custom p-1">
        <a class="navbar-brand" href="@Url.Action("Index", "RestaurantBranches")">Our Restaurants</a>
        <div class="collapse navbar-collapse" id="nav-content">
            <ul class="navbar-nav" id="nav-content">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "RestaurantBranches")">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Create", "Reservation")">Reservation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "WantedAd")">We Are Hiring</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Create", "JobApplication")">Submit Job Application</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="main-title">
        <h1>Welcome to Our Restaurant</h1>
        <button class="btn-transparent" type="button" onclick="location.href='@Url.Action("Create", "Reservation")'">Reservation Now</button>
    </div>
    <div>
        @RenderBody()
    </div>
    @RenderSection("Scripts", false)
</body>
</html>